sudo: required
language: ruby

before_install: 
- docker build -t gabriprat/hoshinplan .
- docker run gabriprat/hoshinplan /run.sh
- docker ps -a
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker run /exec bundle exec rake test
- docker push

addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
services:
  - docker
  - redis
