
language: ruby
sudo: false
cache: bundler

before_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli
install:
  - gem install bundler --version '1.17.3'
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - export REPO=gabriprat/hoshinplan
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - export COMMIT=$TRAVIS_COMMIT
  - echo TAGS $REPO:$COMMIT - $REPO:$TAG - $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker build -f Dockerfile -t $REPO:$COMMIT -t $REPO:$TAG -t $REPO:travis-$TRAVIS_BUILD_NUMBER .
  - docker push $REPO --all-tags
  - ./bin/bump-task.sh travis-$TRAVIS_BUILD_NUMBER
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle install
  - bundle exec rake db:test:prepare
services:
  - docker
  - redis-server
rvm:
  - ruby-2.5.7
