sudo: false
language: ruby
cache: bundler

before_install: 
  - gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  - rvm get head
  - rvm use jruby-9.0.5.0 --install --binary --fuzzy --ignore-gemsets
  - gem install bundler

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - export REPO=gabriprat/hoshinplan
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
addons:
  postgresql: "9.4"
  code_climate:
    repo_token: 5636a9b21787d77dd5012723
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:test:prepare
  - rake db:test:prepare
services:
  - docker
  - redis
#rvm:
#  - jruby-9.0.5.0
env: JRUBY_OPTS="--server -J-Xmn1024m -J-Xms2048m -J-Xmx2048m" rvm_autoinstall_bundler_flag=1 rvm_install_on_use_flag=1
